routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('products.index'));
});

Auth::routes();

Route::get('/home', 'ProductController@index')->name('home');

Route::post('transactions/paypal/create', 'TransactionController@paypal_store')->name('paypal.store');
Route::delete('/cart/clear','CartController@clearCart')->name('carts.clear');
Route::resource('products','ProductController');
Route::resource('categories','CategoryController');
Route::resource('carts','CartController');
Route::resource('transactions', 'TransactionController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use Illuminate\Http\Request;
use Auth;
use Session;
use Str;
use App\Product;
use App\Status;


class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $statuses = Status::all();

        if(Auth::user()->role_id === 1)
        {
            $transactions = Transaction::all();
        }
        else
        {
             $transactions = Transaction::where('user_id', Auth::user()->id)->get();
        }
        // dd($transactions);
        return view('transactions.index')
             ->with('transactions',$transactions)
             ->with('statuses',$statuses);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
       // flow:
        // 1.create an entry in transactions table with the ff attributes
            //transaction number->unique
            //user_id
        // 2.add an entry/entries transaction_product linked to the newly created enrtyin transaction table
        // 3. compute the total price
        // 4. update the total attribute of the newly created entry in transaction
        // 5. clear cart session

        // ================================================================

        // 1.create an entry in transactions table with the ff attributes
             $transaction =  new Transaction;
                //transaction number->unique
                     // userid+randomcharacter+time
                 $transaction_number= Auth::user()->id.Str::random(10).time();
                 //user_id
                 $user_id = Auth::user()->id;
                 
            $transaction->transaction_number = $transaction_number;
            $transaction->user_id = $user_id;
            $transaction->save();

            // 2.add an entry/entries transaction_product linked to the newly created enrtyin transaction table
                // 2.1. get the keys from the session;this contains the products the user wants to buy
                $cart_ids = array_keys(Session::get('cart'));

                // 2.2. use the aray of product id to find it in the database
                $products = Product::find($cart_ids);

                // dd(Session::get('cart'));
                //  2.3. for every products listed in the cart,add entry to the pivot table transaction product and include data(subtotal,quantity,price, product_id, and transaction_id)

                // dd($products);

                // $transaction->products()->attach(//id of reference table--product);
                // $product->transactions()->attach(//)

                foreach (Session::get('cart') as $cart_order_id => $quantity) {
                    foreach($products as $product){
                        if($product->id == $cart_order_id){
                            $transaction->products()->attach(
                                $product->id,
                                [
                                    'quantity' => $quantity,
                                    'price' => $product->price,
                                    'subtotal' => $quantity * $product->price

                                ]
                            );
                        }
                    }
                }

                // 3. compute the total price

                $total=0;
                $transaction_products = $transaction->products;
                // dd($transaction_products);
                foreach ($transaction_products as $transaction_product) {
                      $total+= $transaction_product->pivot->subtotal;
                }

                // 4. update the total attribute of the newly created entry in transaction
                $transaction->total = $total;
                $transaction->save();

                 // 5. clear cart session
                Session::forget('cart');
                return redirect(route('transactions.show',['transaction'=> $transaction->id]) );

              
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        // echo "showing single $transaction";
        $this-> authorize('view', $transaction);
        return view('transactions.show')->with('transaction',$transaction);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        $transaction->status_id = $request ->input('status');
        $transaction->save();
        return redirect(route('transactions.index') )->with('updated_transaction',$transaction->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        //
    }

    public function paypal_store(Request $request)
    {
        $data = json_decode($request->getContent(), true);
        $transaction =  new Transaction;
        $transaction_number = $data['transactionNumber'];
        // $transaction_number= Auth::user()->id.Str::random(10).time();
        $user_id = Auth::user()->id;

               
        $transaction->transaction_number = $transaction_number;
        $transaction->user_id = $user_id;
        $transaction->payment_mode_id = 2;
        $transaction->save();

        // Ready data for pivot table
        $cart_ids = array_keys(Session::get('cart'));
        $products = Product::find($cart_ids);
 
        // add entry in pivot table
        foreach (Session::get('cart') as $cart_order_id => $quantity) {
            foreach($products as $product){
                if($product->id == $cart_order_id){
                    $transaction->products()->attach(
                        $product->id,
                        [
                            'quantity' => $quantity,
                            'price' => $product->price,
                            'subtotal' => $quantity * $product->price

                        ]
                    );
                }
            }
        }

                    // 3. compute the total price

        $total=0;
        $transaction_products = $transaction->products;
                    // dd($transaction_products);
        foreach ($transaction_products as $transaction_product) {
                          $total+= $transaction_product->pivot->subtotal;
        }

                    // 4. update the total attribute of the newly created entry in transaction
        $transaction->total = $total;
        $transaction->save();

                     // 5. clear cart session
        Session::forget('cart');




        return ["url"=> route('transactions.show',['transaction' => $transaction->id])];
    }
}

resources/views/transactions/index.blade.php
@extends('layouts.app')
@section('content')

<div class="conrtainer">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			{{-- start of accordion --}}
			<div class="accordion" id="accordionExample">

				@foreach($transactions as $transaction)
				<div class="card shadow">
					<div class="card-header" id="headingOne">
						<h2 class="mb-0">
						<button class="btn btn-link w-100" type="button" data-toggle="collapse" data-target="#transaction-{{$transaction->id}}" aria-expanded="false" aria-controls="collapseOne">
						{{ $transaction->transaction_number}} / {{$transaction->created_at->format('F d,Y -h:i:s')}} 
								@if(Session::has('updated_transaction') && Session::get('updated_transaction') == $transaction->id)

									<span class="badge badge-info"> Status Updated </span>
								@endif

								@if($transaction->status->name == "pending")
								<span class="badge badge-warning float-right">
									{{$transaction->status->name}}
								</span>
								@elseif($transaction->status->name == "complete")
								<span class="badge badge-success float-right">
									{{$transaction->status->name}}
								</span>
								@endif
						</button>
						</h2>
					</div>
					<div id="transaction-{{$transaction->id}}" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
						<div class="card-body">
							{{-- start of card body --}}
							<h5 class="card-title text-center">Summary</h5>
							<div class="table-responsive mb-3">

								{{-- start of table --}}
								<table class="table table-sm table-borderless">
						<tbody>
							{{-- <tr>
								<img src="{{url('../../public/images'.$product->image) }}" >
							</tr> --}}
							<tr>
								<td>Customer Name:</td>
								<td><strong>{{ $transaction->user->name}}</strong></td>
							</tr>
							<tr>
								<td>Transaction Number:</td>
								<td><strong>{{ strtoupper($transaction->transaction_number)}}</strong></td>
							</tr>
							<tr>
								<td>Mode of payment:</td>
								<td>{{ $transaction->payment_mode->name}}</td>
							</tr>
							<tr>
								<td>Status:</td>
								<td>{{ $transaction->status->name}}

									@cannot('isUser')
									<form action="{{ route('transactions.update',['transaction'=>$transaction->id])}}" method="POST" class="p-3 bg-secondary rounded">
										@csrf
										@method('PUT')
										<label for="edit-transaction-{{$transaction->id}}">Change Status</label>
										<select class="custom-select mb-1" id="edit-transaction-{{$transaction->id}}" name="status">

											@foreach($statuses as $status)
											<option value="{{$status->id}}"
												{{-- @if($status->id == $transaction->status_id)
													selected
													@endif --}} 
													{{--  Same --}}

												{{$status->id == $transaction->status_id ? "selected" : ""}}
												>{{$status->name}}
											</option>
											@endforeach

										</select>

										<button class="btn btn-primary w-180">Change Status</button>

									</form>
									@endcannot

								</td>
							</tr>
							<tr>
								<td>Date:</td>
								<td>{{$transaction->created_at->format('F d,Y')}}</td>
							</tr>

							<tr>
								<td>Total:</td>
								<td>
									&#8369;
									{{ number_format($transaction->total,2)}}
								</td>
							</tr>
						</tbody>
						<tfoot>
							<tr>
								<td colspan="2">
									<a href="{{route('transactions.show',['transaction'=>$transaction->id])}}" class="btn btn-primary">View Details</a>
								</td>
							</tr>
						</tfoot>
					</table>

								{{-- end of table --}}
							</div>

							{{-- end of card body --}}
						</div>
					</div>
				</div> {{-- end of card --}}

				@endforeach
				
			</div>
			{{-- end of accordion --}}
			
		</div>
	</div>
</div>
@endsection

resources/views/transactions/show.blade.php
@extends('layouts.app')
@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">Transaction Details</h3>
			</div>
		</div> {{-- end of row --}}

		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<div class="tableble-responsive">
					<table class="table table-sm table-borderless">
						<tbody>
							<tr>
								<td>Customer Name:</td>
								<td><strong>{{ $transaction->user->name}}</strong></td>
							</tr>
							<tr>
								<td>Transaction Number:</td>
								<td><strong>{{ strtoupper($transaction->transaction_number)}}</strong></td>
							</tr>
							<tr>
								<td>Mode of payment:</td>
								<td>{{ $transaction->payment_mode->name}}</td>
							</tr>
							<tr>
								<td>Status:</td>
								<td>{{ $transaction->status->name}}</td>
							</tr>
							<tr>
								<td>Date:</td>
								<td>{{$transaction->created_at->format('F d,Y')}}</td>
							</tr>
						</tbody>
					</table>

					<table class="table">
						<thead>
							<th scope="col">Name:</th>
							<th scope="col">Quantity:</th>
							<th scope="col">Unit Price:</th>
							<th scope="col">Amount:</th>

						</thead>
						<tbody>
							@foreach($transaction->products as $itemsintransaction)
						

							<tr> {{-- per product --}}
								<td>{{$itemsintransaction->name }}</td>
								<td>{{$itemsintransaction->pivot->quantity }}</td>
								<td>&#8369; <span>{{number_format($itemsintransaction->pivot->price,2) }}</span></td>
								<td>&#8369; <span>{{number_format($itemsintransaction->pivot->subtotal,2) }}</span></td>
							</tr>
							@endforeach
						</tbody>
						<tfoot>
							<tr>
								<th scope="row" colspan="3" class="text-right">Total:</th>
								<td>&#8369; <span>{{number_format($transaction->total,2) }}</span></td>
							</tr>
						</tfoot>
					</table>
				</div>

			</div>
		</div>
	</div>
{{-- {{dd($transaction_item)}} --}}


@endsection