routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('products.index'));
});

Auth::routes();

Route::get('/home', 'ProductController@index')->name('home');

Route::post('transactions/paypal/create', 'TransactionController@paypal_store')->name('paypal.store');
Route::delete('/cart/clear','CartController@clearCart')->name('carts.clear');
Route::resource('products','ProductController');
Route::resource('categories','CategoryController');
Route::resource('carts','CartController');
Route::resource('transactions', 'TransactionController');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{

	use SoftDeletes;

    public function category()
    {

        return $this->belongsTo('App\Category'); 
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use App\Category;
use Str;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('products.index')->with('products', $products);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Product $product)
    {
        $this->authorize('create',$product);

        $categories = Category::all();
        return view('products.create')->with('categories',$categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Product $product)
    {

        $this->authorize('create',$product);
        //flow
            // 1.validate each field(validation errors will display in views)
            // 2. save uploaded image (to get the path which will be save to the database)
            // 3. get input values from form
            // 4. save to details to the database
            // 5. redirect user to view the newly created product

        //====================================================================

          // 1.validate each field(validation errors will display in views)
            $request->validate([
                'name' => 'required|string',
                'price' => 'required|numeric',
                'category' =>'required',
                'image' => 'required|image|max:2000',
                'description' => 'required|string'
            ]);


            // 2. save uploaded image (to get the path which will be save to the database)

                //2.1. get uploaded file
                    $file =$request->file('image');
                    
                //2.2. get uploaded filename
                    $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);

                //2.3. get uploaded file extension name
                    $file_extension = $file->extension();

                //2.4. generate new name with random characters
                    $random_chars = Str::random(10);

                    $new_file_name = date('Y-m-d-H-i-s')."_".$random_chars."_" .$file_name.".".$file_extension;
                    // dd($new_file_name);
                //2.5. save the new file to public folder
                    $filepath = $file->storeAs('images',$new_file_name, 'public');

            // 3. get input values from form
                    $name = $request->input('name');
                    $price = $request->input('price');
                    $category_id = $request->input('category');
                    $description = $request->input('description');
                    $image = $filepath;

            // 4. save to details to the database
                    $product = new Product;
                    $product->name = $name;
                    $product->price = $price;
                    $product->category_id = $category_id;
                    $product->description = $description;
                    $product->image = $image;

                    $product->save();


            // 5. redirect user to view the newly created product
                    return redirect(route('products.show',['product'=>$product->id]));





    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show')->with('product',$product);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)

    {
        $this->authorize('update', $product);
        $categories = Category::all();
        return view('products.edit')
            ->with('product',$product)
            ->with('categories', $categories);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $this->authorize('update', $product);
        //flow
            // 1. validate the form,check if all fields are not empty,except  image input
            // 2. upadate database if there are differences bet the details from form and the current details of the product

                // =============================================================

        // 1. validate the form,check if all fields are not empty,except  image input
                 $request->validate([
                'name' => 'required|string',
                'price' => 'required|numeric',
                'category' =>'required',
                // 'image' => 'required|image|max:2000',
                'description' => 'required|string'
            ]);

        // 2. upadate database if there are differences bet the details from form and the current details of the product

                 if(
                    !$request->hasFile('image') &&
                    $product->name == $request->input('name') &&
                    $product->description == $request->input('description') &&
                    $product->price == $request->input('price') &&
                    $product->category_id == $request->input('category')
                 )
                {
                    $request ->session()->flash('update_failed', 'Something went wrong');
                    // return redirect( route('products.edit',['product' =>$product->id]));
                }else{
                    //update the entry in the database and return the update entry

                    //check if there's a file uploaded
                    if($request->hasFile('image'))
                    {
                        $request->validate([
                            'image' => 'required|image|max:2000'
                        ]);

                    $file =$request->file('image');
                    $file_name = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
                    $file_extension = $file->extension();
                    $random_chars = Str::random(10);

                    $new_file_name = date('Y-m-d-H-i-s')."_".$random_chars."_" .$file_name.".".$file_extension;
                    
                    $filepath = $file->storeAs('images',$new_file_name, 'public');

                    //set the new image path as image prooduct
                    $product->image =$filepath;
                    }

                    //update the product attribute
                    $product->name =$request->input('name');
                    $product->price =$request->input('price');
                    $product->description =$request->input('description');
                    $product->category_id =$request->input('category');

                    $product->save();

                    $request->session()->flash('update_success','Product successfully updated');

                }

                return redirect(route('products.show',['product' => $product->id]));

 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $this->authorize('delete', $product);
        $product->delete();
        // $request->session()->flash('destroy_success','Product Destroyed');
        return redirect(route('products.index'))
        ->with('destroy_message','Product Destroyed');
    }
}

resources/views/products/create.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<h3 class="text-center">
			Add Product
			</h3>
			<hr>
			<form action=" {{ route('products.store')}}" method="POST" enctype="multipart/form-data">
				@csrf
				
				{{-- input for name --}}
				<div class="form-group">
					<label for="name">Product name:</label>
					<input type="text" name="name" class="form-control" id="name">
				</div>
				@if($errors->has('name'))
				<div class="alert alert-danger">
					<small class="mb-0">Product name required</small>
				</div>
				@endif

				{{-- input for price--}}
				<div class="form-group">
					<label for="price">Product price:</label>
					<input
					type="number"
					name="price"
					class="form-control"
					id="price"
					min="1"
					>
				</div>
				@if($errors->has('price'))
				<div class="alert alert-danger">
					<small class="mb-0">Product price required</small>
				</div>
				@endif

				{{-- input for categor --}}
				<div class="form-group">
					<label for="category">Product Category:</label>
					<select class="form-control" id="category" name="category">
						@foreach($categories as $category)
						<option value="{{$category->id}}">{{$category->name}}
						</option>
						@endforeach
					</select>
				</div>
				@if($errors->has('category'))
				<div class="alert alert-danger">
					<small class="mb-0">Product category required</small>
				</div>
				@endif

				{{-- input for image--}}
				<div class="form-group">
					<label for="image">Product image:</label>
					<input
					type="file"
					name="image"
					class="form-control-file"
					id="image"
					min="1"
					>
				</div>
				@if($errors->has('price'))
				<div class="alert alert-danger">
					<small class="mb-0">Product image required: Check if image is not greater than 2 MB</small>
				</div>
				@endif

				{{-- input for description--}}
				<div class="form-group">
					<label for="description">Product description:</label>
					<textarea
					id="description"
					class="form-control"
					cols="30"
					rows="10"
					name="description"></textarea>
				</div>
				@if($errors->has('description'))
				<div class="alert alert-danger">
					<small class="mb-0">Product description required</small>
				</div>
				@endif

				<div>
					<button class="btn btn-primary btn-block" > Add Item</button>
				</div>
			</form> {{-- add product form --}}
		</div> {{-- end of add product form --}}

		{{-- clumn for add category form --}}

		<div>
			<div class="col-12 col-md-12 mx-auto">
				@if(Session::has('category_message')) {{-- true or false --}}
					<div class="alert alert-success">
						{{ Session::get('category_message')}} {{-- GET displays the session --}}
					</div>
				@endif
				@if($errors->has('add-category'))
					<div class="alert alert-danger">
						Category not added
					</div>
				@endif
				
				<form method="POST" action="{{route('categories.store')}}">
					@csrf
					<div class="form-group">
						<label for="add-category">Add category:</label>
						<input type="text" name="add-category" id="add-category" class="form-control">
					</div>

					<button class="btn btn-secondary w-100">Add category</button>
				</form>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
	<div class="row">
		<div class="col-12 col-md-8 mx-auto">
			<h3 class="text-center">
			Edit Product
			</h3>
			<hr>
			@if (Session::has('update_failed'))
				<div class="alert alert-warning">
					{{ Session::get('update_failed')}}
				</div>
			@endif
			@if (Session::has('update_success'))
				<div class="alert alert-success">
					{{ Session::get('update_success')}}
				</div>
			@endif
			<form action=" {{ route('products.update',['product'=> $product->id])}}" method="POST" enctype="multipart/form-data">
				@csrf
				@method('PUT')
				
				{{-- input for name --}}
				<div class="form-group">
					<label for="name">Product name:</label>
					<input type="text" name="name" class="form-control" id="name" class="form-control" value ="{{$product->name}}">
				</div>
				@if($errors->has('name'))
				<div class="alert alert-danger">
					<small class="mb-0">Product name required</small>
				</div>
				@endif
				{{-- input for price--}}
				<div class="form-group">
					<label for="price">Product price:</label>
					<input
					type="number"
					name="price"
					class="form-control"
					id="price"
					min="1"
					value ="{{$product->price}}"
					>
				</div>
				@if($errors->has('price'))
				<div class="alert alert-danger">
					<small class="mb-0">Product price required</small>
				</div>
				@endif
				{{-- input for category --}}
				<div class="form-group">
					<label for="category">Product Category:</label>
					<select class="form-control" id="category" name="category">
						@foreach($categories as $category)
						<option
							value="{{$category->id}}"
							@if($product->category_id == $category->id)
							selected
							@endif>{{$category->name}}
						</option>
						@endforeach
					</select>
				</div>
				@if($errors->has('category'))
				<div class="alert alert-danger">
					<small class="mb-0">Product category required</small>
				</div>
				@endif
				{{-- input for image--}}
				<div class="form-group">
					<label for="image">Product image:</label>
					<input
					type="file"
					name="image"
					class="form-control-file"
					id="image"
					min="1"
					>
				</div>
				@if($errors->has('price'))
				<div class="alert alert-danger">
					<small class="mb-0">Product image required: Check if image is not greater than 2 MB</small>
				</div>
				@endif
				{{-- input for description--}}
				<div class="form-group">
					<label for="description">Product description:</label>
					<textarea
					id="description"
					class="form-control"
					cols="30"
					rows="10"
					name="description">{{$product->description}}</textarea>
				</div>
				@if($errors->has('description'))
				<div class="alert alert-danger">
					<small class="mb-0">Product description required</small>
				</div>
				@endif
				<div>
					<button class="btn btn-primary btn-block" >Edit Item</button>
				</div>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')

@if (Session::has('destroy_success'))
<div class="alert alert-success">
	{{Session::get('destroy_success')}}
</div>
@endif
<div class="container">
	<div class="row">
		<div class="col">
			<div class="jumbotron shadow">
				<h1 class="text-center">For All Clothing Store</h1>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-12 col-md-12">
			<div class="row">
				
				@foreach($products as $product)
				<div class="col-12 col-md-4 col-lg-3 my-2">
					<div class="card shadow" id="itemcard">
						<!-- <div class="card-img-top" id="image-container"> -->
							<img src="{{url('/public/'.$product->image) }}" id="imagecard" class="card-img-top img-fluid">
						<!-- </div> -->
						<div class="card-body">
							<div class="card-foot">

								@cannot('isAdmin')
								<form action="{{route('carts.store')}}" method="post" class="add-to-cart-field">
									<div class="form-group">
										@csrf
										<input type="hidden" name="id" value="{{$product->id}}">
										<label for="quantity">Quantity:</label>

										{{-- Start of append button --}}
										<div class="input-group mb-3">
											<div class="input-group-prepend">
												<button class="btn btn-outline-secondary deduct-quantity" type="button" data-id="{{$product->id}}">-</button>
											</div>

											<input type="number" name="quantity" class="form-control input-quantity" data-id="{{$product->id}}" placeholder="Enter quantity">

											<div class="input-group-append">
												<button class="btn btn-outline-secondary add-quantity" type="button" data-id="{{$product->id}}">+</button>
											</div>
										</div>
										{{-- End of append button --}}
									</div>
								
									<button  type="submit" class="btn btn-outline-success my-1 w-100">Add to Cart
									</button>
								</form>
								
								@endcannot
								
								{{-- View button --}}
								<a
									href="{{route('products.show',['product' =>$product->id])}}"
									class="btn btn-primary w-100 my-1">View Product
								</a>

								@can('isAdmin')
								{{-- Edit button --}}
								<a
									href="{{route('products.edit',['product'=> $product ->id])}}"
									class="w-100 btn btn-warning my-1">Edit Product
								</a>
								{{-- Delete form --}}
								<form action="{{route('products.destroy',['product' =>$product->id])}}" method="POST">
									@csrf
									@method('DELETE')
									<button class="btn btn-danger w-100 my-1"> Delete Product</button>
									
								</form>
								@endcan
								
							</div>
							<h2 class="card-title">
							{{$product->name}}
							</h2>
							<p> {{$product->category->name}}</p>
							<p class="card-text">
								<strong>
								&#8369 {{$product->price}}
								</strong>
							</p>
							<p class="card-text">
								{{$product->description}}
							</p>

						</div>
					</div>
				</div>
				@endforeach
			</div>
			
			
		</div>
	</div>
</div>
@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')

	<div class="container">
		<div class="row">
			<div class="col-12 col-md-8 mx-auto">
				<h3 class="text-center">
					View Product
				</h3>
				<hr>

				<div class="card shadow">
					<img src="{{url('/public/'.$product->image) }}" 
					class="card-img-top single">
					<div class="card-body">
						<div class="card-foot">

							@cannot('isAdmin')
							<form action="{{route('carts.store')}}" method="post" class="add-to-cart-field">
									<div class="form-group">
										@csrf
										<input type="hidden" name="id" value="{{$product->id}}">
										<label for="quantity">Quantity:</label>

										{{-- Start of append button --}}
										<div class="input-group mb-3">
											<div class="input-group-prepend">
												<button class="btn btn-outline-secondary deduct-quantity" type="button" data-id="{{$product->id}}">-</button>
											</div>

											<input type="number" name="quantity" class="form-control input-quantity" data-id="{{$product->id}}" placeholder="Enter quantity">

											<div class="input-group-append">
												<button class="btn btn-outline-secondary add-quantity" type="button" data-id="{{$product->id}}">+</button>
											</div>
										</div>
										{{-- End of append button --}}
									</div>
								
									<button  type="submit" class="btn btn-success my-1 w-100">Add to Cart
									</button>
								</form>
								@endcannot
								
							{{-- View button --}}
							{{-- <a 
								href="{{route('products.show',['product' =>$product->id])}}" 
								class="btn btn-primary w-100 my-1">View Product
							</a>
 --}}
							{{-- Edit button --}}
							{{-- @cannot('isUser') --}}
							@can('isAdmin')
							<a 
								href="{{route('products.edit',['product'=> $product->id])}}" 
								class="w-100 btn btn-warning my-1">Edit Product
							</a>

							{{-- Delete form --}}
							<form action="{{route('products.destroy',['product' =>$product->id])}}" method="POST">
								@csrf
								@method('DELETE')
								<button class="btn btn-warning w-100 my-1"> Delete Product</button>
								
							</form>
							@endcan
							{{-- @endcannot --}}
							
							
						</div>
						<h2 class="card-title">
						{{$product->name}}
						</h2>

						<p class="card-text">
							<strong>
								&#8369 {{$product->price}}
							</strong>
						</p>
						<p class="card-text">
							{{$product->description}}
						</p>
					</div>
				</div> 
				{{-- endof card --}}

			</div>
		</div>
	</div>

@endsection